### ISSUE TITLE
Scheduler breaks after upgrade to 4.5.1

### ISSUE THREAD

**Issue by sksksksk** [tpwd/ke_search#128]
After upgrading to 4.5.1 I get the following error when the scheduler cron job runs or when I try to view the scheduler tasks in the backend

Uncaught TYPO3 Exception Too few arguments to function Tpwd\KeSearch\Indexer\IndexerRunner::__construct(), 0 passed in /home/www/typo3_src-10.4.32/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3496 and exactly 1 expected
thrown in file /home/www/prod/typo3conf/ext/ke_search/Classes/Indexer/IndexerRunner.php
in line 90

TYPO3 version 10
PHP version 7.4
non composer installation

**Comment by sksksksk** [comment]
this issue fixed by itself after repeatedly clearing caches in the installer tool.
