### ISSUE TITLE
ArgumentCountError after Update to 4.5.0 and or 4.5.1

### ISSUE THREAD

**Issue by Batman777** [tpwd/ke_search#130]
When trying to open the sysfolder to start the indexing I get the following error. Typo3 10.4.32

ArgumentCountError

Too few arguments to function Tpwd\KeSearch\Indexer\IndexerRunner::__construct(), 0 passed in /var/www/vhosts/DOMAIN.de/httpdocs/typo3_src-10.4.32/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3496 and exactly 1 expected

P.S.
Just saw that this was already an issue when I tried to update from  4.4.5 -> 4.5.0

Any help appreciated :)

**Comment by christianbltr** [comment]
I could not reproduce the issue on my 10.4.32 test instance (composer installation).

* Are you on a composer or a legacy installation?
* Did you try to clear the dependency injection cache (module "Maintenance" --> "Flush TYPO3 and PHP Cache")?

**Comment by Batman777** [comment]
It is a legacy installation!
And thank you very much for the tip. Again it was an cache issue 😲.

**Comment by Batman777** [comment]
Wenn ich nun die Vollständige Indizierung starte bekomme ich folgendes.

` (1/2) Doctrine\DBAL\Exception\DriverException

An exception occurred while executing 'SELECT pages.*, GROUP_CONCAT(CONCAT("#", tx_kesearch_filteroptions.tag, "#")) as tags FROM `pages`, `tx_kesearch_filteroptions` WHERE (pages.uid IN (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,1 etc`

und

`httpdocs/typo3_src-10.4.32/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 110`

und noch viele andere Fehler in Dateien :-(

**Comment by christianbltr** [comment]
Please create a new issue and insert the complete error message there, thank you.

**Comment by Batman777** [comment]
Issue was solved with the version 4.6.2

**Comment by fischhase** [comment]
Dear Contributors,
I have the same prob: After updating the ext ke_search I get an error message at running the cron scheduler:run:

Uncaught TYPO3 Exception Too few arguments to function Tpwd\KeSearch\Indexer\IndexerRunner::__construct(), 1 passed in /usr/www/users/XXX/typo3/typo3_src-11.5.26/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3249 and exactly 2 expected
thrown in file /usr/www/users/XXX/web/domain.de/typo3conf/ext/ke_search/Classes/Indexer/IndexerRunner.php
in line 93

Subject of the TYPO3 schedular error mail is: Cron [xxx@xxx](mailto:xxx@xxx) '/usr/bin/flock' -n -E 0 '/usr/home/xxx/.tmp/3f36cb8d8d9e65f5ab10ffcc8f6f8224.lck' '/bin/bash' -c '/usr/bin/php74 /usr/www/users/xxx/web/domain.de/typo3/sysext/core/bin/typo3 scheduler:run'

Opening the Schedular Module, the error message appears:
Too few arguments to function Tpwd\KeSearch\Indexer\IndexerRunner::__construct(), 1 passed in /usr/www/users/xxx/typo3/typo3_src-11.5.26/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3249 and exactly 2 expected

Hope you know a solution. Thank you
