### ISSUE TITLE
Scheduler breaks after upgrade to 5.4.0

### ISSUE THREAD

**Issue by KHReinhardt** [tpwd/ke_search#220]
After an update to ke_search 5.4.0 we get the following error message when trying to open Scheduler:

ArgumentCountError, code #0, file \ke_search\Classes\Indexer\IndexerRunner.php, line 92: Too few arguments to function Tpwd\KeSearch\Indexer\IndexerRunner::__construct(), 2 passed in \typo3_src\typo3\sysext\core\Classes\Utility\GeneralUtility.php on line 3247 and exactly 3 expected

Setup:
- PHP 8.1
- Typo3 11.5.36
- ke_search 5.4.0

**Comment by mbsued** [comment]
Same here with Typo3  12.4.14:
Core: Exception handler (CLI): Uncaught TYPO3 Exception: Too few arguments to function Tpwd\KeSearch\Indexer\IndexerRunner::__construct(), 2 passed in /html/typo3/typo3_src-12.4.14/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3016 and exactly 3 expected | ArgumentCountError thrown in file /html/typo3/typo3conf/ext/ke_search/Classes/Indexer/IndexerRunner.php in line 92

**Comment by christianbltr** [comment]
I could not reproduce this issue.

Are you in a composer based or "classic" installation?
Did you try flushing the dependency injection cache either using `vendor/bin/typo3 cache:flush` or using the backend module "Maintanance" --> "Flush TYPO3 and PHP Cache"?

**Comment by KHReinhardt** [comment]
Flushing the dependency injection cache did it for me/us. Thanks for the hint.
And thank you for your great work on the extension, it's much appreciated!
