### ISSUE TITLE
Exception in backend with ke_search 4.4.0 on PHP 7.4 

### ISSUE THREAD

**Issue by bzgaLindner** [tpwd/ke_search#88]
Hi,

after Update to 4.4.0 (and emptying cache) I get the following error when opening ke-search backend module:

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: Too few arguments to function Tpwd\KeSearch\Domain\Repository\IndexRepository::__construct(), 0 passed in .../xyz/typo3_src-10.4.27/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3480 and exactly 1 expected | ArgumentCountError thrown in file /abc/typo3conf/ext/ke_search/Classes/Domain/Repository/IndexRepository.php in line 42. Requested URL: [myDomain]/typo3/index.php?route=%%2Fmodule%%2Fweb%%2FKeSearchBackendModule&token=--AnonymizedToken--&id=45&

I have tree indexer configs in an indexing folder.

Downgrading to v 4.3.1 helps.

[And thanks for this super great Extension!!]

**Comment by christianbltr** [comment]
The argument for IndexRepository is registered in Configuration/Services.yaml which is cached in the core cache (https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/DependencyInjection/Index.html#configure-dependency-injection-in-extensions).

Did you try to delete the lowlevel cache (backend module "Maintanance" --> "Flush TYPO3 and PHP Cache")?

**Comment by cmoldaschl** [comment]
I have the same issue. Can be reproduced
- Install Extension 4.4.0
- backend module "Maintanance" --> "Flush TYPO3 and PHP Cache"
- Red Box appears: "Clearing caches failed
Clearing caches went wrong on the server side. Check the system for broken extensions or missing database tables and try again."
- Message: "(1/1) ParseError
syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)" in /var/www/htdocs/typo3conf/ext/ke_search/Classes/Indexer/Filetypes/Doc.php line 44

**Comment by christianbltr** [comment]
@cmoldaschl  
That looks like you are using PHP 7.2. ke_search requires PHP 7.4. since version 4.4.0. Unfortunately the PHP version constraint was missing in that version, that has been fixed in version 4.4.1 (as of today).

From the error message it also does not look like the same issue as initially reported in this issue.

**Comment by bzgaLindner** [comment]
@christianbltr : thanks, flushing typo3 cache helped with version 4.4.1
